pipeline {
    agent any
    
    options {
        skipStagesAfterUnstable()
    }
        
    stages {
        
        /*stage('Init') {
        *   steps {
        *       sh 'maven clean -f FrameWork/pom.xml'
        *   }
        *}
        */
        
        stage('Build') {
            steps {
                sh 'maven install -B -DskipTests -f TestPractice/pom.xml'
            }
        }
        stage('Test') {
            steps {
                sh 'maven test -f TestPractice/pom.xml'
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deploy to Tomcat9') { 
            steps {
                deploy adapters: [tomcat9(credentialsId: 'tomcat9_credentialsId', url: 'http://192.168.0.102:5000')], war: '**/*.war'
            }
        }
    }
}